stages:
  - publish
  - deploy

variables:
  TAG_BACKEND: $CI_REGISTRY_IMAGE/backend:latest

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$ID_RSA" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - touch ~/.ssh/known_hosts
  - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

publish-job:
  image: docker
  stage: publish
  tags:
    - publish
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $TAG_BACKEND ./CEOClubs-CRM-Backend
    - docker push $TAG_BACKEND
  only:
    refs:
      - main


deploy-job:
  image: docker:stable
  stage: deploy
  tags:
    - deployment
  script:
    - ssh $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY"
    - ssh $SERVER_USER@$SERVER_IP "docker pull $TAG_BACKEND"
    - ssh $SERVER_USER@$SERVER_IP "docker compose up -d backend"
  only:
    refs:
      - main

